config/routes.rb
Folld::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "my_devise/sessions" }

  get 'tag/:tag', to: 'links#index', as: :tag
  resources :links
  root to: 'links#index'
  
  match '/:username' => 'links#index', :as => :user_links

  match '/:username/:tag' => 'links#index', :as => :user_links_by_tag

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :description, :private, :title, :uri, :tag_list
  
  validates_presence_of :title
  
  validates_each :uri do |record, attr, value|
  	if !(value =~ URI::regexp)
	  	record.errors.add(attr, 'Must be a valid URL')
  	end
  end
  
  acts_as_taggable
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  validates_presence_of :username
  validates_exclusion_of :username, :in => %w(tag admin user users), :message => 'Sorry, that user name is reserved.'
  # Note: %w is shorthand for ['some', 'thing']

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(user)
	 user_links_path(current_user.username)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  respond_to :html, :js
  before_filter :authenticate_user!, except: [:index, :show]
  
  # GET /links
  def index
    # TODO: Get friendly URLs on search results:
    # http://stackoverflow.com/questions/8528288/submitting-a-rails-form-to-a-friendly-url
    # Maybe switch to rocket tag too. for easier multiple tag searches
    # https://github.com/bradphelan/rocket_tag
    if params[:username] && params[:tag]
      @links = User.find_by_username(params[:username]).links.tagged_with(params[:tag]).order('updated_at desc').page params[:page]
    elsif params[:username]
      @links = User.find_by_username(params[:username]).links.order('updated_at desc').page params[:page]
    elsif params[:tag] && !params[:tag].empty?
      @links = Link.tagged_with(params[:tag]).page params[:page]
    else
      @links = Link.order('updated_at desc').includes(:user).page params[:page]
    end
    respond_with(@links)
  end

  def show
    @link = Link.find(params[:id])
    respond_with(@link)
  end

  # GET /links/new
  def new
    @link = Link.new
    respond_with(@link)
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
    respond_with(@link)
  end

  # POST /links
  def create
    @link = Link.new(params[:link])
    @link.user = current_user

    if @link.save
      flash[:notice] = 'Link created.'
    end
    respond_with(@link)
  end

  # PUT /links/1
  def update
    @link = Link.find(params[:id])
    if @link.user == current_user
      if @link.update_attributes(params[:link])
        flash[:notice] = 'Link updated.'
      end
    else
      flash[:error] = "You can't update other people's links"
    end
    respond_with(@link)
  end

  # DELETE /links/1
  def destroy
    @link = Link.find(params[:id])
    if @link.user == current_user
      @link.destroy
      flash[:notice] = 'Link deleted.'
      @destroyed = true
    else
      flash[:error] = "You can't delete other people's links"
    end
    respond_with(@link)
  end
end

app/controllers/my_devise/sessions_controller.rb
class MyDevise::SessionsController < Devise::SessionsController

	# Note: Original one of these is in:
	# ~/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/gems/2.0.0/gems/devise-2.2.3/app/controllers/devise/sessions_controller.rb
	
	respond_to :html, :js

	def new
		super
	end

	def create
		super
	end

	def destroy
		super
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
		case level
			when :notice then "alert alert-info"
			when :success then "alert alert-success"
			when :error then "alert alert-error"
			when :alert then "alert alert-error"
		end
	end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/_flash_messages.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>">
      <div class="icon close-white pull-right"><span>Close</span></div>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Folld</title>
    <meta name="viewport" content="width=device-width">
    <link href='http://fonts.googleapis.com/css?family=Oxygen:700,300' rel='stylesheet' type='text/css'>
    <!-- <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'> -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>

    <header class="clearfix">
        <div id="site_logo">
            <%= link_to content_tag(request.fullpath == '/' ? :h1 : :span, 'Folld'), root_path %>
            <div class="icon-large slash-grey"></div>
        </div>
        <% if params[:username] then %>
            <div class="user">
                <div class="icon-large user-grey"></div><%= params[:username] %>
            </div>
            <div class="icon-large slash-grey"></div>
        <% end %>
        <%= form_tag links_path, :id => 'search', :method => 'get' do %>
            <%= text_field_tag :tag, params[:tag] %>
            <%= submit_tag "Go", :name => nil %>
        <% end %>

        <nav id="user_nav">
            <% if user_signed_in? %>
                <div class="logged_in_as">Logged in as <%= link_to current_user.email, edit_user_registration_path %></div>
                <%= link_to 'My Links', user_links_path(current_user.username) %>
                <%= link_to "Logout", destroy_user_session_path, :class => 'logout', method: :delete %>
            <% else %>
                <%= link_to "Sign up", new_user_registration_path %>
                <%= link_to "Login", new_user_session_path, :remote => true %>
            <% end %>
            <a href="#" class="icon-large tags-grey pull-right" id="show-tags"><span>Tags</span></a>
        </nav>

        <%= render 'layouts/flash_messages' %>
        
    </header>

    <%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link, :remote => true do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uri, "URL" %><br />
    <%= f.text_field :uri, :placeholder => 'http://' %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <div class="cancel">Cancel</div>
  </div>
<% end %>

app/views/links/_link.html.erb
<div class="link tiles_item" id="link_<%= link.id %>">
	<div class="show">
		<h4 class="title"><%= link_to link.title, link.uri, :rel => 'nofollow' %></h4>
		<div class="description"><%= link.description %></div>
		<div class="meta">
			<div class="user"><div class="icon-small user-grey"><span>By: </span></div><%= link_to link.user.username, user_links_path(link.user.username) rescue "No user" %></div>
		    <% if(link.tag_list.length>0) then %>
		    	<div class="tags"><div class="icon-small tags-grey inline"><span>Tags: </span></div><%= raw link.tag_list.map { |t| link_to t, tag_path(t) }.join(' ') %></div>
		    <% end %>
		    <% if(link.user == current_user) %>
		    	<div class="actions">
			    	<%= link_to '', edit_link_path(link), :class => 'icon-small edit-grey', :title => 'Edit', :remote => true %>
			    	<%= link_to '', link, :class => 'icon-small close-grey', :title => 'Remove', method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %>
			    </div>
			<% end %>
		</div>
	</div>
</div>

app/views/links/create.js.erb
console.log("create.js.erb called");
<%= render :partial => 'shared/flash_messages' %>
<% if @link.save %>
	$('#new_link').remove(); // Remove Form
	$('#add_new_link').show();
	$('#links').prepend('<%= j render(@link) %>');
<% else %>
	$('#new_link').html('<%= j render("form") %>');
<% end %>

app/views/links/destroy.js.erb
<%= render :partial => 'shared/flash_messages' %>
<% if @destroyed %>
	$('#link_<%= @link.id %>').remove();
<% end %>

app/views/links/edit.html.erb
<h2>Editing link</h2>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/edit.js.erb
// Hide any other forms
$('.link').each(function(){
	if($('.edit_link', this).length>0) {
		$('.edit_link', this).hide();
		$('.show', this).show();
	}
});
$('.new_link_action form').remove();
$('.new_link_action a').removeClass('active');


// Show new form
$('#link_<%= @link.id %> .show').hide().after('<%= j render("form") %>');

app/views/links/index.html.erb
<div id="main" class="links_view">
	<div class="tiles_outer">
		<div class="tiles_inner">
			<div class="tiles_item new_link_action">
				<%= link_to '+ New Link', new_link_path, :id => 'add_new_link', :remote => current_user ? true : false  %>
			</div>
			<div id="links">
				<% @links.each do |link| %>
					<%= render link %>
				<% end %>
			</div>
			<div class="tiles_item">
				<%= paginate @links %>
			</div>
		</div>
	</div>
</div>

<footer>
	<%= render :partial => 'shared/tag_cloud' %>
</footer>

app/views/links/new.html.erb
<h2>New link</h2>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/new.js.erb
<%= render :partial => 'shared/flash_messages' %>

$('.link').each(function(){
	if($('.edit_link', this).length>0) {
		$('.edit_link', this).hide();
		$('.show', this).show();
	}
});
$('#add_new_link').addClass('active').after('<%= j render("form") %>');

app/views/links/show.html.erb
<%= render @link %>

app/views/links/update.js.erb
<%= render :partial => 'shared/flash_messages' %>
$('#link_<%= @link.id %>').replaceWith('<%= j render(@link) %>');

app/views/shared/_flash_messages.js.erb
<% if flash[:error] %>
	folld.flash('error', '<%= j flash[:error] %>');
<% elsif flash[:notice] %>
	folld.flash('notice', '<%= j flash[:notice] %>');
<% end %>

app/views/shared/_tag_cloud.html.erb
<div id="tag_cloud">
	<h3>Tags</h3>
	<% tag_cloud Link.tag_counts, %w[s m l] do |tag, css_class| %>
    	<%= link_to tag.name, tag_path(tag.name), class: css_class %>
	<% end %>
</div>